### ISSUE TITLE
rpm build failed scst 3.9 on Rocky Linux 9.6

### ISSUE THREAD

**Issue by pzwahlen** [SCST-project/scst#294]
RL 9.6 was just released with kernel 5.14.0-570.18.1.el9_6.x86_64. Building latest 3.9 tag (34d3a4) fails with this error:
```
make[3]: Entering directory '/usr/src/kernels/5.14.0-570.18.1.el9_6.x86_64'
  CC [M]  /home/nsp/temp-dWKo/BUILD/nv_scst-3.9-34d3a4git/scst/src/scst_copy_mgr.o
In file included from /home/nsp/temp-dWKo/BUILD/nv_scst-3.9-34d3a4git/scst/src/../include/scst.h:71,
                 from /home/nsp/temp-dWKo/BUILD/nv_scst-3.9-34d3a4git/scst/src/scst_copy_mgr.c:16:
/home/nsp/temp-dWKo/BUILD/nv_scst-3.9-34d3a4git/scst/src/../include/backport.h: In function 'get_user_pages_backport':
/home/nsp/temp-dWKo/BUILD/nv_scst-3.9-34d3a4git/scst/src/../include/backport.h:721:16: error: too many arguments to function 'get_user_pages'
  721 |         return get_user_pages(start, nr_pages, gup_flags, pages, NULL);
      |                ^~~~~~~~~~~~~~
In file included from ./arch/x86/include/asm/cacheflush.h:5,
                 from ./include/linux/cacheflush.h:5,
                 from ./include/linux/highmem.h:8,
                 from ./include/linux/bvec.h:10,
                 from ./include/linux/blk_types.h:10,
                 from ./include/linux/blkdev.h:9,
                 from /home/nsp/temp-dWKo/BUILD/nv_scst-3.9-34d3a4git/scst/src/../include/scst.h:37,
                 from /home/nsp/temp-dWKo/BUILD/nv_scst-3.9-34d3a4git/scst/src/scst_copy_mgr.c:16:
./include/linux/mm.h:2476:6: note: declared here
 2476 | long get_user_pages(unsigned long start, unsigned long nr_pages,
      |      ^~~~~~~~~~~~~~
make[4]: *** [scripts/Makefile.build:249: /home/nsp/temp-dWKo/BUILD/nv_scst-3.9-34d3a4git/scst/src/scst_copy_mgr.o] Error 1
make[3]: *** [Makefile:1947: /home/nsp/temp-dWKo/BUILD/nv_scst-3.9-34d3a4git/scst/src] Error 2
make[3]: Leaving directory '/usr/src/kernels/5.14.0-570.18.1.el9_6.x86_64'
make[2]: *** [Makefile:83: all] Error 2
make[2]: Leaving directory '/home/nsp/temp-dWKo/BUILD/nv_scst-3.9-34d3a4git/scst/src'
make[1]: *** [Makefile:36: all] Error 2
make[1]: Leaving directory '/home/nsp/temp-dWKo/BUILD/nv_scst-3.9-34d3a4git/scst'
make: *** [Makefile:184: scst] Error 2
error: Bad exit status from /home/nsp/temp-dWKo/TMP/rpm-tmp.r6rDAt (%build)
```

**Comment by pzwahlen** [comment]
Hmm, I just realise the master branch contains fixes for EL/RL 9.6

Is there a timeframe already for pushing these to the 3.9 branch ?

**Comment by lnocturno** [comment]
Hi,

Thank you for the report! Please try again with the latest changes.

Thanks,
Gleb

**Comment by pzwahlen** [comment]
3.9 compiles perfectly on RL9.6 !

Thanks!

**Comment by leofrestic** [comment]
I am facing similar problems when installing SCST on RHEL 9.6 with kernel 5.14.0-570.24.1.el9_6.x86_64.

error: too many arguments to function â€˜get_user_pagesâ€™
[2025-07-24 08:24:31]   721 |         return get_user_pages(start, nr_pages, gup_flags, pages, NULL);

Also can you guide me to get the **scst-3.9.tar.gz** this bundle
