### ISSUE TITLE
3.11-pre build on rhel8 4.18.0-553.126.1.el8_10.x86_64 -->error: missing binary operator before token

### ISSUE THREAD

**Issue by caihuazhg** [SCST-project/scst#377]
make[4]: Leaving directory '/usr/src/packages/BUILD/scst-3.11.0.0/scst/src/certs'
make -C /lib/modules/4.18.0-553.126.1.el8_10.x86_64/build M=/usr/src/packages/BUILD/scst-3.11.0.0/scst/src				\
  
make[4]: Entering directory '/usr/src/kernels/4.18.0-553.126.1.el8_10.x86_64'
  CC [M]  /usr/src/packages/BUILD/scst-3.11.0.0/scst/src/scst_copy_mgr.o
In file included from /usr/src/packages/BUILD/scst-3.11.0.0/scst/src/../include/scst.h:71,
                 from /usr/src/packages/BUILD/scst-3.11.0.0/scst/src/scst_copy_mgr.c:16:
/usr/src/packages/BUILD/scst-3.11.0.0/scst/src/../include/backport.h:1313:44: error: missing binary operator before token "("
 #if defined(__has_builtin) && __has_builtin(__builtin_counted_by_ref)
                                            ^
make[5]: *** [scripts/Makefile.build:318: /usr/src/packages/BUILD/scst-3.11.0.0/scst/src/scst_copy_mgr.o] Error 1
make[4]: *** [Makefile:1619: _module_/usr/src/packages/BUILD/scst-3.11.0.0/scst/src] Error 2
make[4]: Leaving directory '/usr/src/kernels/4.18.0-553.126.1.el8_10.x86_64'
make[3]: *** [Makefile:83: all] Error 2
make[3]: Leaving directory '/usr/src/packages/BUILD/scst-3.11.0.0/scst/src'
make[2]: *** [Makefile:36: all] Error 2
make[2]: Leaving directory '/usr/src/packages/BUILD/scst-3.11.0.0/scst'
error: Bad exit status from /var/tmp/rpm-tmp.xmT4yK (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.xmT4yK (%build)
make[1]: *** [Makefile:378: scst-rpm] Error 1
make[1]: Leaving directory '/root/scst-master'
make: *** [Makefile:416: rpm] Error 2

**Comment by lnocturno** [comment]
Hi

Thank you for the report!

Thanks,
Gleb
