### ISSUE TITLE
Unable to build on Centos Stream 8

### ISSUE THREAD

**Issue by bennycdr** [SCST-project/scst#77]
I'm trying to build scst on a clean install of Centos 8 Stream and getting the following errors:

]# BUILD_2X_MODULE=y CONFIG_SCSI_QLA_FC=y CONFIG_SCSI_QLA2XXX_TARGET=y make all install
if [ all = extraclean ]; then rm -f TAGS tags cscope.out; fi
for d in scst iscsi-scst qla2x00t-32gbit/qla2x00-target srpt        \
        scst_local fcst usr scstadmin; do \
        make -j$(nproc) -C "$d" all || break;               \
done
make[1]: Entering directory '/root/scst/scst'
cd src && make all
make[2]: Entering directory '/root/scst/scst/src'
make -C certs KDIR=/lib/modules/4.18.0-408.el8.x86_64/build                                     \

make[3]: Entering directory '/root/scst/scst/src/certs'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/root/scst/scst/src/certs'
make -C /lib/modules/4.18.0-408.el8.x86_64/build M=/root/scst/scst/src                          \

make[3]: Entering directory '/usr/src/kernels/4.18.0-408.el8.x86_64'
  CC [M]  /root/scst/scst/src/scst_copy_mgr.o
  CC [M]  /root/scst/scst/src/scst_debug.o
  CC [M]  /root/scst/scst/src/scst_dlm.o
  CC [M]  /root/scst/scst/src/scst_event.o
  CC [M]  /root/scst/scst/src/scst_lib.o
  CC [M]  /root/scst/scst/src/scst_local_cmd.o
  CC [M]  /root/scst/scst/src/scst_main.o
  CC [M]  /root/scst/scst/src/scst_mem.o
  CC [M]  /root/scst/scst/src/scst_no_dlm.o
  CC [M]  /root/scst/scst/src/scst_pres.o
  CC [M]  /root/scst/scst/src/scst_sysfs.o
  CC [M]  /root/scst/scst/src/scst_targ.o
In file included from /root/scst/scst/src/../include/scst.h:64,
                 from /root/scst/scst/src/scst_copy_mgr.c:17:
/root/scst/scst/src/../include/backport.h:1473:31: error: redefinition of ‘scsi_cmd_to_rq’
 static inline struct request *scsi_cmd_to_rq(struct scsi_cmnd *scmd)
                               ^~~~~~~~~~~~~~
In file included from /root/scst/scst/src/../include/scst.h:54,
                 from /root/scst/scst/src/scst_copy_mgr.c:17:
./include/scsi/scsi_cmnd.h:171:31: note: previous definition of ‘scsi_cmd_to_rq’ was here
 static inline struct request *scsi_cmd_to_rq(struct scsi_cmnd *scmd)
                               ^~~~~~~~~~~~~~
In file included from /root/scst/scst/src/../include/scst.h:64,
                 from /root/scst/scst/src/scst_copy_mgr.c:17:
/root/scst/scst/src/../include/backport.h:1497:19: error: redefinition of ‘scsi_prot_ref_tag’
 static inline u32 scsi_prot_ref_tag(struct scsi_cmnd *scmd)
                   ^~~~~~~~~~~~~~~~~
In file included from /root/scst/scst/src/../include/scst.h:54,
                 from /root/scst/scst/src/scst_copy_mgr.c:17:
./include/scsi/scsi_cmnd.h:327:19: note: previous definition of ‘scsi_prot_ref_tag’ was here
 static inline u32 scsi_prot_ref_tag(struct scsi_cmnd *scmd)
                   ^~~~~~~~~~~~~~~~~
In file included from /root/scst/scst/src/../include/scst.h:64,
                 from /root/scst/scst/src/scst_debug.c:31:
/root/scst/scst/src/../include/backport.h:1473:31: error: redefinition of ‘scsi_cmd_to_rq’
 static inline struct request *scsi_cmd_to_rq(struct scsi_cmnd *scmd)
                               ^~~~~~~~~~~~~~
In file included from /root/scst/scst/src/../include/scst.h:54,
                 from /root/scst/scst/src/scst_debug.c:31:
./include/scsi/scsi_cmnd.h:171:31: note: previous definition of ‘scsi_cmd_to_rq’ was here
 static inline struct request *scsi_cmd_to_rq(struct scsi_cmnd *scmd)
                               ^~~~~~~~~~~~~~
In file included from /root/scst/scst/src/../include/scst.h:64,
                 from /root/scst/scst/src/scst_debug.c:31:
/root/scst/scst/src/../include/backport.h:1497:19: error: redefinition of ‘scsi_prot_ref_tag’
 static inline u32 scsi_prot_ref_tag(struct scsi_cmnd *scmd)
                   ^~~~~~~~~~~~~~~~~
In file included from /root/scst/scst/src/../include/scst.h:54,
                 from /root/scst/scst/src/scst_debug.c:31:
./include/scsi/scsi_cmnd.h:327:19: note: previous definition of ‘scsi_prot_ref_tag’ was here
 static inline u32 scsi_prot_ref_tag(struct scsi_cmnd *scmd)
                   ^~~~~~~~~~~~~~~~~
In file included from /root/scst/scst/src/../include/scst.h:64,
                 from /root/scst/scst/src/scst_event.c:26:
/root/scst/scst/src/../include/backport.h:1473:31: error: redefinition of ‘scsi_cmd_to_rq’
 static inline struct request *scsi_cmd_to_rq(struct scsi_cmnd *scmd)
                               ^~~~~~~~~~~~~~
In file included from /root/scst/scst/src/../include/scst.h:54,
                 from /root/scst/scst/src/scst_event.c:26:
./include/scsi/scsi_cmnd.h:171:31: note: previous definition of ‘scsi_cmd_to_rq’ was here
 static inline struct request *scsi_cmd_to_rq(struct scsi_cmnd *scmd)
                               ^~~~~~~~~~~~~~
In file included from /root/scst/scst/src/../include/scst.h:64,
                 from /root/scst/scst/src/scst_event.c:26:
/root/scst/scst/src/../include/backport.h:1497:19: error: redefinition of ‘scsi_prot_ref_tag’
 static inline u32 scsi_prot_ref_tag(struct scsi_cmnd *scmd)
                   ^~~~~~~~~~~~~~~~~
In file included from /root/scst/scst/src/../include/scst.h:54,
                 from /root/scst/scst/src/scst_event.c:26:
./include/scsi/scsi_cmnd.h:327:19: note: previous definition of ‘scsi_prot_ref_tag’ was here
 static inline u32 scsi_prot_ref_tag(struct scsi_cmnd *scmd)
                   ^~~~~~~~~~~~~~~~~
make[4]: *** [scripts/Makefile.build:315: /root/scst/scst/src/scst_debug.o] Error 1
make[4]: *** Waiting for unfinished jobs....
In file included from /root/scst/scst/src/../include/scst.h:64,
                 from /root/scst/scst/src/scst_dlm.c:26:
/root/scst/scst/src/../include/backport.h:1473:31: error: redefinition of ‘scsi_cmd_to_rq’
 static inline struct request *scsi_cmd_to_rq(struct scsi_cmnd *scmd)
                               ^~~~~~~~~~~~~~
In file included from /root/scst/scst/src/../include/scst.h:54,
                 from /root/scst/scst/src/scst_dlm.c:26:
./include/scsi/scsi_cmnd.h:171:31: note: previous definition of ‘scsi_cmd_to_rq’ was here
 static inline struct request *scsi_cmd_to_rq(struct scsi_cmnd *scmd)
                               ^~~~~~~~~~~~~~
In file included from /root/scst/scst/src/../include/scst.h:64,
                 from /root/scst/scst/src/scst_dlm.c:26:
/root/scst/scst/src/../include/backport.h:1497:19: error: redefinition of ‘scsi_prot_ref_tag’
 static inline u32 scsi_prot_ref_tag(struct scsi_cmnd *scmd)
                   ^~~~~~~~~~~~~~~~~
In file included from /root/scst/scst/src/../include/scst.h:54,
                 from /root/scst/scst/src/scst_dlm.c:26:
./include/scsi/scsi_cmnd.h:327:19: note: previous definition of ‘scsi_prot_ref_tag’ was here
 static inline u32 scsi_prot_ref_tag(struct scsi_cmnd *scmd)
                   ^~~~~~~~~~~~~~~~~
In file included from /root/scst/scst/src/../include/scst.h:64,
                 from /root/scst/scst/src/scst_lib.c:54:
/root/scst/scst/src/../include/backport.h:1473:31: error: redefinition of ‘scsi_cmd_to_rq’
 static inline struct request *scsi_cmd_to_rq(struct scsi_cmnd *scmd)
                               ^~~~~~~~~~~~~~
In file included from /root/scst/scst/src/../include/scst.h:54,
                 from /root/scst/scst/src/scst_lib.c:54:
./include/scsi/scsi_cmnd.h:171:31: note: previous definition of ‘scsi_cmd_to_rq’ was here
 static inline struct request *scsi_cmd_to_rq(struct scsi_cmnd *scmd)
                               ^~~~~~~~~~~~~~
In file included from /root/scst/scst/src/../include/scst.h:64,
                 from /root/scst/scst/src/scst_lib.c:54:
/root/scst/scst/src/../include/backport.h:1497:19: error: redefinition of ‘scsi_prot_ref_tag’
 static inline u32 scsi_prot_ref_tag(struct scsi_cmnd *scmd)
                   ^~~~~~~~~~~~~~~~~
In file included from /root/scst/scst/src/../include/scst.h:54,
                 from /root/scst/scst/src/scst_lib.c:54:
./include/scsi/scsi_cmnd.h:327:19: note: previous definition of ‘scsi_prot_ref_tag’ was here
 static inline u32 scsi_prot_ref_tag(struct scsi_cmnd *scmd)
                   ^~~~~~~~~~~~~~~~~
In file included from /root/scst/scst/src/../include/scst.h:64,
                 from /root/scst/scst/src/scst_local_cmd.c:22:
/root/scst/scst/src/../include/backport.h:1473:31: error: redefinition of ‘scsi_cmd_to_rq’
 static inline struct request *scsi_cmd_to_rq(struct scsi_cmnd *scmd)
                               ^~~~~~~~~~~~~~
In file included from /root/scst/scst/src/../include/scst.h:54,
                 from /root/scst/scst/src/scst_local_cmd.c:22:
./include/scsi/scsi_cmnd.h:171:31: note: previous definition of ‘scsi_cmd_to_rq’ was here
 static inline struct request *scsi_cmd_to_rq(struct scsi_cmnd *scmd)
                               ^~~~~~~~~~~~~~
In file included from /root/scst/scst/src/../include/scst.h:64,
                 from /root/scst/scst/src/scst_local_cmd.c:22:
/root/scst/scst/src/../include/backport.h:1497:19: error: redefinition of ‘scsi_prot_ref_tag’
 static inline u32 scsi_prot_ref_tag(struct scsi_cmnd *scmd)
                   ^~~~~~~~~~~~~~~~~
In file included from /root/scst/scst/src/../include/scst.h:54,
                 from /root/scst/scst/src/scst_local_cmd.c:22:
./include/scsi/scsi_cmnd.h:327:19: note: previous definition of ‘scsi_prot_ref_tag’ was here
 static inline u32 scsi_prot_ref_tag(struct scsi_cmnd *scmd)

Any help would be appreciated.  Kernel is: 4.18.0-408.el8.x86_64. I've tried 3.6.x stable as well as the master branch with the same error. 
 Compiles fine on Centos 7.9.

**Comment by lnocturno** [comment]
Hi,

Thank you for the report. I will take a look at this on the next week.

Thanks,
Gleb

**Comment by lnocturno** [comment]
Hi,

Sorry for the long response.
I have fixed this issue in commit https://github.com/SCST-project/scst/commit/fa1a8e1ee5026b546677c2d0bb7f0c5ebeec71f6

And also ported it to the stable 3.6.x branch so you can use it.
https://github.com/SCST-project/scst/tree/3.6.x

Thanks,
Gleb
