### ISSUE TITLE
compat with kernel 6.13

### ISSUE THREAD

**Issue by limbo127** [SCST-project/scst#273]
Hello, 
fyi, cannot compile with latest stable kernel 6.13.x 
Regards,

( The parameter of MODULE_IMPORT_NS has been changed from constants to string literal: https://github.com/torvalds/linux/commit/cdd30ebb1b9f36159d66f088b61aee264e649d7a. ) 

cc -c -o iscsi_adm.o -O2 -Wall -Wextra -Wstrict-prototypes -Wno-sign-compare -Wimplicit-function-declaration -Wno-unused-parameter -Wno-missing-field-initializers -Wno-format-truncation -g -I../include -I../../scst/include -D_GNU_SOURCE   iscsi_adm.c
  CC [M]  iscsi.o
  CC [M]  nthread.o
  CC [M]  config.o
  CC [M]  digest.o
  CC [M]  conn.o
  CC [M]  session.o
cc iscsi_adm.o param.o   -o iscsi-scst-adm
  CC [M]  target.o
cc iscsid.o iscsi_scstd.o conn.o session.o target.o message.o ctldev.o log.o chap.o event.o param.o config.o isns.o md5.o sha1.o misc.o   -o iscsi-scstd
make[2]: Leaving directory '/tmp/workdir/test/modules/scst/iscsi-scst/usr'
  CC [M]  event.o
  CC [M]  param.o
In file included from /tmp/workdir/test/kernel/linux-6.13/include/linux/module.h:22,
                 from iscsi.c:17:
iscsi.c:4299:18: error: expected ',' or ';' before 'SCST'
 4299 | MODULE_IMPORT_NS(SCST);
      |                  ^~~~
/tmp/workdir/test/kernel/linux-6.13/include/linux/moduleparam.h:26:61: note: in definition of macro '__MODULE_INFO'
   26 |                 = __MODULE_INFO_PREFIX __stringify(tag) "=" info
      |                                                             ^~~~
/tmp/workdir/test/kernel/linux-6.13/include/linux/module.h:299:33: note: in expansion of macro 'MODULE_INFO'
  299 | #define MODULE_IMPORT_NS(ns)    MODULE_INFO(import_ns, ns)
      |                                 ^~~~~~~~~~~
iscsi.c:4299:1: note: in expansion of macro 'MODULE_IMPORT_NS'
 4299 | MODULE_IMPORT_NS(SCST);
      | ^~~~~~~~~~~~~~~~
  CC [M]  iscsit_transport.o
make[5]: *** [/tmp/workdir/test/kernel/linux-6.13/scripts/Makefile.build:194: iscsi.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [/tmp/workdir/test/kernel/linux-6.13/Makefile:1989: .] Error 2
make[3]: *** [/tmp/workdir/test/kernel/linux-6.13/Makefile:251: __sub-make] Error 2
make[3]: Leaving directory '/tmp/workdir/test/modules/scst/iscsi-scst/kernel'
make[2]: *** [Makefile:251: __sub-make] Error 2
make[2]: Leaving directory '/tmp/workdir/test/kernel/linux-6.13'
make[1]: *** [Makefile:141: mods] Error 2
make[1]: Leaving directory '/tmp/workdir/test/modules/scst/iscsi-scst'
make: *** [Makefile:238: iscsi] Error 2

**Comment by limbo127** [comment]
Thanks
Nicolas
